<?php

namespace App\Repositories\Trans;

use App\Models\Trans\Jadwal;
use App\Repositories\BaseRepository;
use Ramsey\Uuid\Uuid;

class JadwalRepository extends BaseRepository
{
    public function __construct(Jadwal $model)
    {
        parent::__construct($model);
    }

    public function data($columns = '*') {
        return $this->model->newQuery()
            ->selectRaw(
                "trans_jadwal.id,
                trans_jadwal.tanggal,
                TO_CHAR(trans_jadwal.tanggal, 'DD Mon YYYY') as ftanggal,
                trans_jadwal.jam_mulai,
                trans_jadwal.jam_selesai,
                mk.id as md_kegiatan_id,
                mk.deskripsi as kegiatan,
                case when mk.id is null then '-' else mk.id end as md_kegiatan_id,
                case when mk.deskripsi is null then '-' else mk.deskripsi end as kegiatan,
                case when sl.nama is null then '-' else sl.nama end as level,
                case when mkel.nama is null then '-' else mkel.nama end as kelompok,
                case when sd.nama is null then '-' else sd.nama end as desa,
                case when sjk.nama is null then '-' else sjk.nama end as jenis_kegiatan,
                case when skj.nama is null then '-' else skj.nama end as peserta"
            )
            ->leftJoin('md_kegiatan as mk', 'trans_jadwal.md_kegiatan_id', '=', 'mk.id')
            ->leftJoin('st_jenis_kegiatan as sjk', 'mk.st_jenis_kegiatan_id', '=', 'sjk.id')
            ->leftJoin('st_kategori_jamaah as skj', 'mk.st_kategori_jamaah_id', '=', 'skj.id')
            ->leftJoin('st_level as sl', 'mk.st_level_id', '=', 'sl.id')
            ->leftJoin('md_kelompok as mkel', 'mk.md_kelompok_id', '=', 'mkel.id')
            ->leftJoin('st_desa as sd', 'mk.st_desa_id', '=', 'sd.id')
            ->whereNull('trans_jadwal.deleted_at')
            ->get();
    }

    public function create($data)
    {
        $data['id'] = Uuid::uuid1()->toString();
        return parent::create($data); // TODO: Change the autogenerated stub
    }
}
