<?php

namespace App\Repositories\Trans;

use App\Models\Trans\Kepengurusan;
use App\Repositories\BaseRepository;
use Ramsey\Uuid\Uuid;

class KepengurusanRepository extends BaseRepository
{
    public function __construct(Kepengurusan $model)
    {
        parent::__construct($model);
    }

    public function data($columns = '*')
    {
        return $this->model->newQuery()
            ->selectRaw(
                "trans_kepengurusan.id,
                trans_kepengurusan.md_jamaah_nik,
                case when mj.nama is null then '-' else mj.nama end as nama_jamaah,
                trans_kepengurusan.md_kepengurusan_id,
                case when mk.nama is null then '-' else mk.nama end as nama_kepengurusan,
                case when sk.nama is null then '-' else sk.nama end as kategori,
                case when sl.nama is null then '-' else sl.nama end as level"
            )
            ->leftJoin('md_jamaah as mj', 'trans_kepengurusan.md_jamaah_nik', '=', 'mj.nik')
            ->leftJoin('md_kepengurusan as mk', 'trans_kepengurusan.md_kepengurusan_id', '=', 'mk.id')
            ->leftJoin('st_kepengurusan as sk', 'mk.st_kepengurusan_id', '=', 'sk.id')
            ->leftJoin('st_level as sl', 'mk.st_level_id', '=', 'sl.id')
            ->whereNull('trans_kepengurusan.deleted_at')
            ->get();
    }

    public function create($data)
    {
        $data['id'] = Uuid::uuid1()->toString();
        return parent::create($data); // TODO: Change the autogenerated stub
    }
}
